### ISSUE TITLE
Dead code?

### ISSUE THREAD

**Issue by andrewluetgers** [Dashed/todomvc-providence#1]
Just reading through the code and noticed what looks to be a dead code-block at   

https://github.com/Dashed/todomvc-providence/blob/master/src/lib/cursor.js#L82-L86

An array is assigned to keyPath and then theres a conditional check for isPlainObject that will return false every time.

**Comment by dashed** [comment]
It's a bad copy/paste :disappointed: Supposed to be `_.isPlainObject(data)` instead of `_.isPlainObject(keyPath)`. Corrected in https://github.com/Dashed/todomvc-providence/commit/eb4a85d9e223f278f249cb990987a848f9dee2cd

**Comment by dashed** [comment]
I should get around to porting cursor tests xD
